### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Pandamoms** [THEREALWWEFAN231/wwe#293]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/2/19 8:54 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.class_4446.method_21558(class_4446.java:72)
	at net.minecraft.class_4446.method_21563(class_4446.java:54)
	at net.minecraft.class_4446$$Lambda$1823/1442863936.run(Unknown Source)
	at com.mojang.blaze3d.platform.GLX.withTextureRestore(GLX.java:251)
	at net.minecraft.class_4446.method_21559(class_4446.java:53)
	at net.minecraft.class_4325$class_4330.method_20946(class_4325.java:1356)
	at net.minecraft.class_4325$class_4330.method_20945(class_4325.java:1241)
	at net.minecraft.class_4325$class_4330.render(class_4325.java:1226)
	at net.minecraft.class_350.renderList(class_350.java:447)
	at net.minecraft.class_350.render(class_350.java:197)
	at net.minecraft.realms.RealmsObjectSelectionList.render(RealmsObjectSelectionList.java:19)
	at net.minecraft.class_4325.render(class_4325.java:794)
	at net.minecraft.realms.RealmsScreenProxy.render(RealmsScreenProxy.java:101)
	at net.minecraft.class_757.method_3192(class_757.java:686)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_4446.method_21558(class_4446.java:72)
	at net.minecraft.class_4446.method_21563(class_4446.java:54)
	at net.minecraft.class_4446$$Lambda$1823/1442863936.run(Unknown Source)
	at com.mojang.blaze3d.platform.GLX.withTextureRestore(GLX.java:251)
	at net.minecraft.class_4446.method_21559(class_4446.java:53)
	at net.minecraft.class_4325$class_4330.method_20946(class_4325.java:1356)
	at net.minecraft.class_4325$class_4330.method_20945(class_4325.java:1241)
	at net.minecraft.class_4325$class_4330.render(class_4325.java:1226)
	at net.minecraft.class_350.renderList(class_350.java:447)
	at net.minecraft.class_350.render(class_350.java:197)
	at net.minecraft.realms.RealmsObjectSelectionList.render(RealmsObjectSelectionList.java:19)
	at net.minecraft.class_4325.render(class_4325.java:794)
	at net.minecraft.realms.RealmsScreenProxy.render(RealmsScreenProxy.java:101)

-- Screen render details --
Details:
	Screen name: net.minecraft.realms.RealmsScreenProxy
	Mouse location: Scaled: (2147483647, 2147483647). Absolute: (701.000000, 479.000000)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:686)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows Vista (amd64) version 6.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 203673976 bytes (194 MB) / 640339968 bytes (610 MB) up to 1060372480 bytes (1011 MB)
	CPUs: 4
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 610 GL version 4.5.0 - Build 25.20.100.6472, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: file/X-Ray Ultimate Resource Pack.zip, vanilla, programer_art
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 4x Intel(R) Pentium(R) CPU 4415U @ 2.30GHz

**Comment by THEREALWWEFAN231** [comment]
This does not exactly look like a crash caused by wwe, also where did it crash, you can reopen this if you would like
