### ISSUE TITLE
Unable to launch because the launcher can not download the files required

### ISSUE THREAD

**Issue by SkilledTheGamer** [THEREALWWEFAN231/wwe#302]
**WWE version:*2.7.2* 
**Minecraft version:*1.13.2* 
**Operating system:*Windows 7* 
**Optifine/Other mods:*Optifine* 

**Whats the issue:*while downloading files from the url* 

**Crash-report(Would be very useful also please format):**
ru.turikhay.tlauncher.downloader.GaveUpDownloadException: http://wweclient.com/me/THEREALWWEFAN231/wwefan/wwe 1.13.2/2.7.2/wwe 1.13.2-2.7.2.jar
at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:189)
at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:84)
Caused by: ru.turikhay.tlauncher.exceptions.IOExceptionList: (4): [Server returned HTTP response code: 403 for URL: http://wweclient.com/me/THEREALWWEFAN231/wwefan/wwe 1.13.2/2.7.2/wwe 1.13.2-2.7.2.jar (cause: java.io.IOException: Server returned HTTP response code: 403 for URL: http://wweclient.com/me/THEREALWWEFAN231/wwefan/wwe 1.13.2/2.7.2/wwe 1.13.2-2.7.2.jar); .....]
at ru.turikhay.tlauncher.downloader.DownloaderThread.download(DownloaderThread.java:189)
at ru.turikhay.tlauncher.downloader.DownloaderThread.run(DownloaderThread.java:84)
Thread called by: ru.turikhay.util.async.ExtendedThread$ExtendedThreadCaller
at ru.turikhay.util.async.ExtendedThread.<init>(ExtendedThread.java:16)
at ru.turikhay.util.async.LoopedThread.<init>(LoopedThread.java:7)
at ru.turikhay.util.async.LoopedThread.<init>(LoopedThread.java:11)
at ru.turikhay.tlauncher.ui.login.LoginForm$StartThread.<init>(LoginForm.java:415)
at ru.turikhay.tlauncher.ui.login.LoginForm.<init>(LoginForm.java:66)
at ru.turikhay.tlauncher.ui.scenes.DefaultScene.<init>(DefaultScene.java:61)
at ru.turikhay.tlauncher.ui.MainPane.<init>(MainPane.java:69)
at ru.turikhay.tlauncher.ui.TLauncherFrame.<init>(TLauncherFrame.java:161)
at ru.turikhay.tlauncher.TLauncher.<init>(TLauncher.java:133)
at ru.turikhay.tlauncher.TLauncher.launch(TLauncher.java:578)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at ru.turikhay.tlauncher.bootstrap.launcher.ClassLoaderStarter$1.execute(ClassLoaderStarter.java:49)
at ru.turikhay.tlauncher.bootstrap.launcher.ClassLoaderStarter$1.execute(ClassLoaderStarter.java:24)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.task.Task.bindTo(Task.java:142)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$3.execute(Bootstrap.java:383)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$3.execute(Bootstrap.java:370)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.task.Task.bindTo(Task.java:142)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$4.execute(Bootstrap.java:428)
at ru.turikhay.tlauncher.bootstrap.Bootstrap$4.execute(Bootstrap.java:389)
at ru.turikhay.tlauncher.bootstrap.task.Task.call(Task.java:79)
at ru.turikhay.tlauncher.bootstrap.Bootstrap.main(Bootstrap.java:126)

**Comment by SkilledTheGamer** [comment]
also i have the files for it but idk where to put it

**Comment by THEREALWWEFAN231** [comment]
Idk why tlauncher does this, so you already downloaded the file, wwe 1.13.2-2.7.2 , if not do so. copy the file to here, make sure everything is spelled correctly!, libraries/me/THEREALWWEFAN231/wwefan/wwe 1.13.2/2.7.2, you will need to make the thoses folders, and copy the wwe 1.13.2-2.7.2.jar to the 2.7.2 folder
