### ISSUE TITLE
bug xcarry crashes when opening donkey/horse inventories

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#314]
**WWE version:** 
latest
**Minecraft version:** 
1.12.2
**Operating system:** 
does not matter
**Optifine/Other mods:** 
none
**Whats the issue:** 
xcarry crashes when opening donkey/horse inventories + as for a suggestion, make xcarry turn off when you exit the game/leave a server
**Crash-report(Would be very useful also please format):**
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiScreenHorseInventory
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

and

java.lang.ArrayIndexOutOfBoundsException: 6
	at java.util.Arrays$ArrayList.set(Arrays.java:3846)
	at net.minecraft.util.NonNullList.set(SourceFile:51)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:100)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

and

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Arrays$ArrayList.set(Arrays.java:3846)
	at net.minecraft.util.NonNullList.set(SourceFile:51)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:100)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

**Comment by THEREALWWEFAN231** [comment]
Couldent replicate... id actually assume it was chest stealer but still couldent replicate
