### ISSUE TITLE
Crash upon connecting to a realms server when HUD is enabled.

### ISSUE THREAD

**Issue by TheGhost567** [THEREALWWEFAN231/wwe#343]
Newest release as of 2-10-2019
1.14.4 
Windows 10 64 Bit 
This issue is not caused by mods as it persists on a fresh installation.

The user is kicked upon connection to a realms server when the HUD module is enabled, it is also not caused by the Color List module as it was disabled during the glitch.

-- Head --
Thread: Client thread
Stacktrace:
	at wwe.Yflc.QTeJ(Unknown Source)
	at wwe.Yflc.OmRC(Unknown Source)
	at wwe.Yflc.DCzm(Unknown Source)
	at net.minecraft.class_329.handler$renderGameOverlay$zbn000(class_329.java:1324)
	at net.minecraft.class_329.method_1753(class_329.java:187)

-- Affected level --
Details:
	All players: 1 total; [class_746['MenMB'/37, l='MpServer', x=775.91, y=95.00, z=-442.70]]
	Chunk stats: Client Chunk Cache: 625, 361
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -88750351473722005994
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-293,56,-82), Chunk: (at 11,3,14 in -19,-6; contains blocks -304,0,-96 to -289,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 22229793 game time, 22523 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:430)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

I did not know what was meant by "please format" so i pasted the useful looking part of the dump, see attachment for full dump.
I also do not know how to get the WWE version number so i did the next best thing and gave the date, please forgive me.

[crash-2019-10-02_22.52.14-client.txt](https://github.com/THEREALWWEFAN231/wwe/files/3683301/crash-2019-10-02_22.52.14-client.txt)

-Ghost (Marcoblo#2202)

**Comment by rushercrack** [comment]
disable ping option in hud

**Comment by THEREALWWEFAN231** [comment]
Go into single player, click gui, hud, and turn ping off, then it will, work, this is next in the next update.
