### ISSUE TITLE
baritone?

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [THEREALWWEFAN231/wwe#398]
baritone crashing? i dont think its due to wwe, but see if i can replicate, then check the original baritone
Just Evan say "Why do I crash every time I open a anvil/crafting table" 
```

java.lang.IndexOutOfBoundsException: toIndex = 54
    at java.util.SubList.<init>(AbstractList.java:622)
    at java.util.AbstractList.subList(AbstractList.java:484)
    at baritone.f.a(Unknown Source)
    at baritone.f$$Lambda$295/1966424552.accept(Unknown Source)
    at java.util.Optional.ifPresent(Optional.java:159)
    at baritone.f.onPlayerUpdate(Unknown Source)
    at baritone.ce.a(Unknown Source)
    at baritone.ce$$Lambda$293/1158122319.accept(Unknown Source)
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
    at baritone.ce.onPlayerUpdate(Unknown Source)
    at net.minecraft.client.entity.EntityPlayerSP.handler$onPreUpdate$zfc000(EntityPlayerSP.java)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:181)
```

Another crash i dont remember who,
```
java.lang.IncompatibleClassChangeError: Expected non-static field baritone.api.utils.BetterBlockPos.field_177990_b
    at baritone.j.a(Unknown Source) ~[j.class:?]
    at baritone.j.onTick(Unknown Source) ~[j.class:?]
    at baritone.y.a(Unknown Source) ~[y.class:?]
    at baritone.y$$Lambda$312/990531620.accept(Unknown Source) ~[?:?]
    at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_51]
    at baritone.y.onTick(Unknown Source) ~[y.class:?]
    at net.minecraft.client.Minecraft.handler$runTick$zee001(Minecraft.java) ~[bib.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755) ~[bib.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by THEREALWWEFAN231** [comment]
Note: definitely baritone
