### ISSUE TITLE
Crashes on Linux (With sudo)

### ISSUE THREAD

**Issue by BenCat07** [THEREALWWEFAN231/wwe#468]
**WWE version:** 
3.0.4
**Minecraft version:** 
1.15.2
**Operating system:** 
(Manjaro KDE) Linux
**Optifine/Other mods:** 
None

**Whats the issue:** 
Crash when anything to do with a Mouse pointer happens (clicking Reconnect when server was unavaiable, Enabling note bot in main menu (Other options are fine apparently), and generally connecting to a server)

Not sure if this is intentional, but the click GUI also only responds to rightclick, not leftclick.

**Crash-report(Would be very useful also please format):**
```
---- Minecraft Crash Report ----
// Oops.

Time: 3/14/20, 10:57 PM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at wwe.QhuX.HIwh(Unknown Source)
	at wwe.QhuX.pqtY(Unknown Source)
	at wwe.AdYV.zpRG(Unknown Source)
	at wwe.GRDa.fOhH(Unknown Source)
	at wwe.GRDa.nzIW(Unknown Source)
	at wwe.OAax.BPyj(Unknown Source)
	at wwe.RmuN.BPyj(Unknown Source)
	at wwe.bggO.mouseClicked(Unknown Source)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at wwe.QhuX.HIwh(Unknown Source)
	at wwe.QhuX.pqtY(Unknown Source)
	at wwe.AdYV.zpRG(Unknown Source)
	at wwe.GRDa.fOhH(Unknown Source)
	at wwe.GRDa.nzIW(Unknown Source)
	at wwe.OAax.BPyj(Unknown Source)
	at wwe.RmuN.BPyj(Unknown Source)
	at wwe.bggO.mouseClicked(Unknown Source)
	at net.minecraft.class_312.method_1611(class_312.java:86)

-- Affected screen --
Details:
	Screen name: wwe.tKBj
Stacktrace:
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.4.24-1-MANJARO
	Java Version: 13.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 528153296 bytes (503 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.187
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 1.5
		wwefan: WWE 1.15.2
	Launched Version: fabric-loader-0.7.8+build.187-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.64, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```

**Comment by THEREALWWEFAN231** [comment]
Try not using open jdk, install the "default" stuff.

**Comment by BenCat07** [comment]
Installed.

**Comment by Paralusion** [comment]
try using JDK1.8.0_162

**Comment by BenCat07** [comment]
it is installed, The question is how do i get minecraft to use it instead of the runtime one?

**Comment by Paralusion** [comment]
all the things you install through AUR are not default/jdk 1.8 162

**Comment by Paralusion** [comment]
join the discord

**Comment by THEREALWWEFAN231** [comment]
Fixed in the discord, he had to use normal java not Open-JDK
